trigger:
  branches:
    include:
      - main

pool: 'mypool'

variables:
  appName: 'elearn-frontend'
  azureSubscription: 'App connection'
  resourceGroup: 'betarg'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(appName)'
    package: '$(System.DefaultWorkingDirectory)/build'
  displayName: 'Deploy React App to Azure'
